In [2]:
import numpy as np

In [11]:
a = 0.1*np.array([[1,2,3],[4,5,6],[7,8,9]])
a  

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6],
       [0.7, 0.8, 0.9]])

In [15]:
exp1 = np.exp(a)
exp1.shape

(3, 3)

In [14]:
exp2 = np.sum(exp1, axis=1)
exp2.shape

(3,)

In [16]:
softmax = exp1/exp2
softmax

array([[0.30060961, 0.24611833, 0.20150464],
       [0.40578052, 0.33222499, 0.27200282],
       [0.54774641, 0.44845683, 0.3671654 ]])

In [20]:
print(a)
b = np.max(a, axis=1)
b

[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]


array([0.3, 0.6, 0.9])

In [21]:
c = np.zeros_like(a)
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
d = a>0.3
d = d*1
d

array([[0, 0, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [7]:
num_train = np.arange(5000)
examples = np.random.choice(num_train, 200)
examples.shape

(200,)

In [8]:
print("{} set".format(1))

1 set
